services:
  - type: web
    name: doc-analysis-api
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SERVICE_API_KEY
        sync: false
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"

